apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: casaprestamosfrontend-deployment
spec:
  selector:
    matchLabels:
      app: casaprestamosfrontend
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: casaprestamosfrontend
    spec:
      containers:
        - name: casaprestamosfrontend
          image: claudiaariash/casa-prestamos-frontend:1.5
          ports:
            - containerPort: 4200
---
kind: Service
apiVersion: v1
metadata:
  name: casaprestamosfrontend-service
spec:
  selector:
    app: casaprestamosfrontend
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
    nodePort: 31000
  type: NodePort
