apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image:  claudiaariash/casaprestamos:3.8
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_SERVICE
            valueFrom:
              configMapKeyRef:
                name: mysql-connection-configmap
                key: db-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name:  app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080