version: '3'

services:

  mysql-dev:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: casaprestamos
    ports:
      - "3308:3306"
      
  mysql-legacy:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: casaprestamos
    ports:
      - "3309:3306"
      
#  client:
#    image: mysql:8.0.23
#    depends_on:
#     - mysql-dev
#    command: mysql -uroot -padmin -hmysql-dev casaprestamos

 